SRC += features/oneshot.c

MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes

RGBLIGHT_ENABLE = no
OLED_ENABLE     = no
OLED_DRIVER     = SSD1306

LTO_ENABLE      = yes

AUTO_SHIFT_ENABLE = yes
TAP_DANCE_ENABLE = yes
CAPS_WORD_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes
COMBO_ENABLE = no

# CONSOLE_ENABLE = yes
