SRC += features/oneshot.c
SRC += features/oled.c

MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes

RGBLIGHT_ENABLE = no
OLED_ENABLE     = yes
OLED_DRIVER     = ssd1306

LTO_ENABLE      = yes

AUTO_SHIFT_ENABLE = yes
TAP_DANCE_ENABLE = yes
CAPS_WORD_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes
COMBO_ENABLE = no

CONSOLE_ENABLE = no
